### ISSUE TITLE
I'm an idiot

### ISSUE THREAD

**Issue by jlotto8** [jlotto8/Rideshare-Project#3]
## Overview

I failed to create a adequate admin settings when I created the project, and have made a lot of changes to fix different problems but I'm not sure I have a good grasp of how those changes are being implemented. 

## Technical Notes
I'm thinking of starting over, and keeping this version for practice with github collaboration. 
Thoughts? 

Also- merge conflicts are hard- but I def pushed changes at the begininng without creating a new branch- which I didn't mean to do, but I think was allowed to do since am the owner/admin despite the branch rules I created.

**Comment by eld120** [comment]
You're doing great work here so I think you can/should continue to iterate on this project. I think you should start your next commit message with "closes #3" to get this issue resolved

**Comment by eld120** [comment]
![image](https://github.com/jlotto8/Rideshare-Project/assets/61638112/4ec7d88b-8155-4909-99bb-0372f0ae8cc6)
@jlotto8  This looks really good for a project you bootstrapped in a couple days, if you can get this done in that amount of time you can get a lot more done in the next few weeks.

**Comment by jlotto8** [comment]
okayyy Ii'l get back to work on it
